"""Draws the 500-word syllable reference list for spec 001 M2 (stdlib only).

Run once from `.sdd/research/` (which holds `cmudict.dict` and `en_50k.txt`):

    python3 ../../docs/specs/001-vernier/measurements/sample_cmudict.py [OUTPUT_DIR]

The loading and sampling code is the syllable spike's (`.sdd/research/syllable_spike.py`),
kept verbatim so the draw is the sample the research measured (regex counter 93.8 %).
Writes `cmudict-500.tsv` (`word<TAB>counts`, counts comma-joined ascending, sorted by word)
into OUTPUT_DIR (default: this script's directory) and prints the spike's regex-counter value
for the first 40 words and for WITNESSES, the tables of the Rust port-fidelity test (plan-M2 P3).
"""
import random
import re
import sys
from collections import defaultdict
from pathlib import Path

# ---------- reference (spike, verbatim) ----------
cmu = defaultdict(set)
for line in open("cmudict.dict", encoding="utf-8"):
    line = line.split("#")[0].strip()
    if not line:
        continue
    head, *phones = line.split()
    word = re.sub(r"\(\d+\)$", "", head)
    if not re.fullmatch(r"[a-z]+", word):
        continue
    cmu[word].add(sum(1 for p in phones if p[-1].isdigit()))

# ---------- regex heuristic (datascience.SE answer 89312; spike, verbatim) ----------
VOWEL_RUNS = re.compile("[aeiouy]+", flags=re.I)
EXCEPTIONS = re.compile("[^aeiou]e[sd]?$|" + "[^e]ely$", flags=re.I)
ADDITIONAL = re.compile(
    "[^aeioulr][lr]e[sd]?$|[csgz]es$|[td]ed$|"
    + ".y[aeiou]|ia(?!n$)|eo|ism$|[^aeiou]ire$|[^gq]ua",
    flags=re.I,
)

def regex_counter(word):
    return max(1, len(VOWEL_RUNS.findall(word)) - len(EXCEPTIONS.findall(word))
               + len(ADDITIONAL.findall(word)))

# ---------- sampling (spike, verbatim) ----------
allwords = sorted(cmu)
freq = []
for line in open("en_50k.txt", encoding="utf-8"):
    w, c = line.split()
    if w in cmu:
        freq.append((w, int(c)))
top20k = [w for w, _ in freq[:20000]]

rng = random.Random(2026)
sample_uniform = rng.sample(allwords, 500)  # kept: it advances the generator to the measured draw
sample_freq = rng.sample(top20k, 500)

# ---------- output ----------
out_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent
rows = sorted(sample_freq)
header = [
    "# 500 frequent English words and their CMUdict syllable counts (one per pronunciation).",
    "# Source: CMUdict (cmusphinx cmudict.dict), BSD-2-style license, see CMUDICT-LICENSE.",
    "# Selection: CMUdict words within the top 20,000 of hermitdave FrequencyWords en_50k (2018, CC BY-SA 4.0),",
    "# random.Random(2026), second 500-draw; generated by sample_cmudict.py.",
]
lines = header + [f"{w}\t{','.join(str(n) for n in sorted(cmu[w]))}" for w in rows]
(out_dir / "cmudict-500.tsv").write_text("\n".join(lines) + "\n", encoding="utf-8")

agree = sum(1 for w in rows if regex_counter(w) in cmu[w])
print(f"python regex_counter agreement: {agree}/{len(rows)}")
print("first 40 words, regex_counter:")
print(", ".join(f'("{w}", {regex_counter(w)})' for w in rows[:40]))

# The first 40 words exercise only two of the nine additions, and no two additions can match at
# the same position, so their order is unobservable; what is observable is that a match is
# consumed before the scan goes on (cronyism, dandyism, mccarthyism, shiyuan: all in CMUdict).
WITNESSES = [
    "people", "places", "wanted", "trying", "special", "asian", "someone", "mechanism",
    "fire", "actually", "quality", "lately", "the", "freely", "biased",
    "cronyism", "dandyism", "mccarthyism", "shiyuan", "nth", "gps",
]
print("witnesses, regex_counter:")
print(", ".join(f'("{w}", {regex_counter(w)})' for w in WITNESSES))
